apiVersion: v1
kind: Service
metadata:
    name: flask-blog-posts-api-service
    namespace: default
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 8080
    selector:
        name: flask-blog-posts-api
